### ISSUE TITLE
lodash: use ES6 methods instead 

### ISSUE THREAD

**Issue by gabrielwelsche** [scottwrobinson/camo#2]
Maybe you can replace some lodash calls to ES6 calls, e.g. there are many new APIs (e.g. Array API)  Instead of _.keys() you can call ["a", "b", "c"].keys() . Please have a look to https://github.com/lukehoban/es6features#readme

**Comment by gabrielwelsche** [comment]
Maybe the ES branch helps a bit: https://github.com/lodash/lodash/tree/es

**Comment by scottwrobinson** [comment]
You're right, there are probably a lot of places we should be using ES6 features and are not. Lodash does, however, use native features underneath when possible (even in the modern, non-ES build). For `_.keys()` it actually first checks that `Object` has the `keys` property, and uses it if it does.

Since native functionality is used when possible, I'll probably stick with the main branch of Lodash for now. Thanks for the suggestion!
