### ISSUE TITLE
Use 'defaultValue' instead of 'default'.

### ISSUE THREAD

**Issue by michaeljota** [scottwrobinson/camo#45]
Because 'default' it's a reserved word.

**Comment by scottwrobinson** [comment]
I don't really see a problem with this since the schema `default` won't ever interfere with JavaScript's `default` keyword. It would only be a problem if you used it as a variable name.

Some linters, like jshint, do highlight it as a keyword, but not because it shouldn't be used, but because their highlighting it fairly naive.

I'm going to leave this as is.

Thanks!
