### ISSUE TITLE
Don't allow to erase documents if they are being referenced in other documents.

### ISSUE THREAD

**Issue by michaeljota** [scottwrobinson/camo#47]
If you delete a document, the referenced id of the other document becomes null, and that's if you save the document with the referenced id.

This is a unexpected behavior. I think it should throw an error to show that's being used.

**Comment by royaltm** [comment]
I don't think it would be easy to implement because mongo/nedb doesn't support foreign key concepts. These are not [relational databases](https://en.wikipedia.org/wiki/Relational_database). They are [document databases](https://en.wikipedia.org/wiki/Document-oriented_database). IMHO the exact behavior as it is, is actually expected.
The relation between documents is just a hack in camo. It's your own responsibility to maintain database integrity. One would need to iterate over all collections containing references to a collection of the document being deleted and query each collection for count of references to the deleted document. Alternative approach would be to store reference counter in the referenced document and quick check it before deletion.
But even then it wouldn't stop you to connect to db back-end directly and mess with your relations, because db engine doesn't care about them.

**Comment by michaeljota** [comment]
Oh! Ok. I did not know that. Thanks! I'll close this.
