### ISSUE TITLE
Document error (findMany -> find)

### ISSUE THREAD

**Issue by tzhuan** [scottwrobinson/camo#54]
In the `Loading` section: 

...match the query. `.findMany()` will return all documents matching the query. ...

`.findMany()` should be `.find()`.

By the way, use `.delete()` instead of `.deleteMany()` might be more consistent:
  - `.deleteOne()` vs. `.findOne()`
  - `.delete()` vs. `find()`

**Comment by scottwrobinson** [comment]
Ah yes, I screwed that up on the last update. Thanks for pointing out the `.findMany()`.

While I agree that it would be more consistent to use `.delete()` instead of `.deleteMany()`, I did it this way because of the Mongo API. For some reason [Mongo uses `.deleteMany()`](http://mongodb.github.io/node-mongodb-native/2.0/api/Collection.html#deleteMany), so that's what I decided to use. However, I'm not totally sold on this, so I may reconsider and change it so the Camo API is more consistent.

Thanks!
